# Generated by Django 4.0.3 on 2024-10-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0005_remove_requisition_bus_remove_requisition_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('selected', 'Selected')], default='available', max_length=10)),
            ],
        ),
    ]
