# Generated by Django 5.1.2 on 2024-10-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0006_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='email',
            field=models.EmailField(default='none@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='requisition',
            name='profession',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='return_date',
            field=models.DateField(),
        ),
    ]
